### ISSUE TITLE
Fatal exception in coroutines machinery for CancellableContinuation

### ISSUE THREAD

**Issue by yvolk** [korlibs/korge-next#156]
I'm getting this exception on Android build from time to time. First time I reported it as a comment in a similar issue in Jetbrains Coroutines repo: https://github.com/Kotlin/kotlinx.coroutines/issues/2413#issuecomment-740381971
But in that issue it was KTor library (which uses Coroutines) that caused the problem, not kotlinx.coroutines themselves (at least as was confirmed in that issue...).

Today I got this exception again on Android device with KorGe Gradle plugin 2.0.6.0 and dependencies as per the build file: https://github.com/andstatus/game2048/blob/1.10.5-release/game2048-android/build.gradle

```
2021-02-06 19:21:33.551 26154-26886/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 20735
    Process: org.andstatus.game2048, PID: 26154
    kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[GameWindowCoroutineDispatcher, Continuation at com.soywiz.korge.tween.TweenKt$tween$3.invokeSuspend(tween.kt:149)@428c54d]){CompletedContinuation(result=kotlin.Unit, cancelHandler=InvokeOnCancel[@807a802], onCancellation=null, idempotentResume=null, cancelCause=kotlinx.coroutines.JobCancellationException: TimeoutCoroutine has completed normally; job=TimeoutCoroutine(timeMillis=302){Completed}@3ff5513)}@f553350. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
        at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending-_rozLdE(GameWindow.kt:111)
        at com.soywiz.korgw.GameWindow.frameUpdate-_rozLdE(GameWindow.kt:384)
        at com.soywiz.korgw.GameWindow.frame-eeKXlv4(GameWindow.kt:317)
        at com.soywiz.korgw.GameWindow.frame-eeKXlv4$default(GameWindow.kt:314)
        at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:311)
        at com.soywiz.korgw.KorgwActivity$onCreate$1$1.onDrawFrame(KorgwActivity.kt:84)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
     Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.internal.DispatchedContinuation
        at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:104)
        at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:226)
        at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending-_rozLdE(GameWindow.kt:111) 
        at com.soywiz.korgw.GameWindow.frameUpdate-_rozLdE(GameWindow.kt:384) 
        at com.soywiz.korgw.GameWindow.frame-eeKXlv4(GameWindow.kt:317) 
        at com.soywiz.korgw.GameWindow.frame-eeKXlv4$default(GameWindow.kt:314) 
        at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:311) 
        at com.soywiz.korgw.KorgwActivity$onCreate$1$1.onDrawFrame(KorgwActivity.kt:84) 
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548) 
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259) 
```

It's hard to reproduce the bug, but as I observe, it occurs, when windows are actively redrawn/animated (in my Open Source app this is when I replay stored game "fast forward").

**Comment by soywiz** [comment]
I reproduced a similar behaviour on the JVM that was fixed here:
https://github.com/korlibs/korge-next/commit/eea0e0c315dbcba17697d06f81751b55626d713f

This was fixed by making the `GameWindowCoroutineDispatcher` thread safe. It seems that Android was using that same dispatcher, so it is likely to be the same problem.
It was pretty hard to reproduce but was more or less consistent on the JVM when also performing asynchronous sockets that put continuations on other threads.

I'm going to asume this is fixed already 👍
