### ISSUE TITLE
Build error: korau:cinteropLinux_OpenALLinuxX64

### ISSUE THREAD

**Issue by dhakehurst** [korlibs/korge-next#22]
> Task :korau:cinteropLinux_OpenALLinuxX64
Exception in thread "main" java.lang.Error: /var/folders/tt/gd5xhny51kg46r_0rwztcsk00000gq/T/tmp16089727685724104985.c:1:10: fatal error: 'AL/al.h' file not found
        at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:152)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:1003)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:992)
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexKt.buildNativeIndex(NativeIndex.kt:91)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:266)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:72)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)
        at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:19)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:37)

> Task :korau:cinteropLinux_OpenALLinuxX64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':korau:cinteropLinux_OpenALLinuxX64'.
> Process 'command '/Library/Java/JavaVirtualMachines/openjdk-12.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5m 29s
692 actionable tasks: 45 executed, 647 up-to-date

**Comment by dhakehurst** [comment]
using a mac to do the build. (macOS v 10.15.5)

**Comment by soywiz** [comment]
Building linux targets on mac is not directly supported. Tried to include linux binaries/header files of the libraries (OpenAL and OpenGL) since linux by default doesn't include those libraries, but was not working properly. You can use `gradlew_linux` (that uses docker) instead or a CI with linux to do that.

**Comment by dhakehurst** [comment]
I actually want to NOT build the linux ones.
I'm building on a mac, but don't need to build the linux targets., However they build by default.

Is it possible to update the gradle script to only build the targets that can be built..i.e. if we can't build linux from a mac, then when trying to build on a mac, it shouldn't try and build them?

**Comment by soywiz** [comment]
Sure, makes sense 👍

**Comment by soywiz** [comment]
This is not an issue anymore
