### ISSUE TITLE
runsJs not working for korge hello world

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge-next#396]
**Describe the bug**

Running runJs on the most latest/up to date commit results in an issue.

My platform:

OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	THINKPAD-X1-YOG
System Manufacturer	LENOVO
System Model	20LDCTO1WW
System Type	x64-based PC
System SKU	LENOVO_MT_20LD_BU_Think_FM_ThinkPad X1 Yoga 3rd
Processor	Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz, 1896 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	LENOVO N25ET56W (1.42 ), 5/12/2021
SMBIOS Version	3.0
Embedded Controller Version	1.21
BIOS Mode	UEFI
BaseBoard Manufacturer	LENOVO
BaseBoard Product	20LDCTO1WW
BaseBoard Version	SDK0J40697 WIN
Platform Role	Mobile
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32

Here are the logs:

```
2021-11-22T02:22:48.863-0800 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :browserReleaseEsbuild FAILED
2021-11-22T02:22:48.863-0800 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Putting task artifact state for task ':browserReleaseEsbuild' into context took 0.0 secs.
2021-11-22T02:22:48.864-0800 [DEBUG] [org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep] Implementation for task ':browserReleaseEsbuild': org.gradle.api.tasks.Exec_Decorated@470bed4de8e56733bd153e760e2c35a4
2021-11-22T02:22:48.864-0800 [DEBUG] [org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep] Additional implementations for task ':browserReleaseEsbuild': [org.gradle.api.tasks.Exec_Decorated@470bed4de8e56733bd153e760e2c35a4]
2021-11-22T02:22:48.864-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Snapshot inputs and outputs before executing task ':browserReleaseEsbuild'' completed
2021-11-22T02:22:48.865-0800 [INFO] [org.gradle.internal.execution.steps.ResolveCachingStateStep] Caching disabled for task ':browserReleaseEsbuild' because:
  Build cache is disabled
2021-11-22T02:22:48.865-0800 [DEBUG] [org.gradle.internal.execution.steps.SkipUpToDateStep] Determining if task ':browserReleaseEsbuild' is up-to-date
2021-11-22T02:22:48.865-0800 [INFO] [org.gradle.internal.execution.steps.SkipUpToDateStep] Task ':browserReleaseEsbuild' is not up-to-date because:
  Task has failed previously.
2021-11-22T02:22:48.865-0800 [DEBUG] [org.gradle.internal.execution.steps.CreateOutputsStep] Ensuring parent directory exists for property $1 at C:\Users\Kiet\git\korge-hello-world\build\www\korge-hello-world.js
2021-11-22T02:22:48.865-0800 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':browserReleaseEsbuild'.
2021-11-22T02:22:48.866-0800 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'C:\Users\Kiet\git\korge-hello-world\build\esbuild\node_modules\esbuild\esbuild.exe''. Working directory: C:\Users\Kiet\git\korge-hello-world Command: C:\Users\Kiet\git\korge-hello-world\build\esbuild\node_modules\esbuild\esbuild.exe --bundle --minify --sourcemap=external C:\Users\Kiet\git\korge-hello-world\build\compileSync\main\productionExecutable\kotlin\korge-hello-world.js --outfile=C:\Users\Kiet\git\korge-hello-world\build\www\korge-hello-world.js
2021-11-22T02:22:48.866-0800 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
2021-11-22T02:22:48.866-0800 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'C:\Users\Kiet\git\korge-hello-world\build\esbuild\node_modules\esbuild\esbuild.exe'.
2021-11-22T02:22:48.867-0800 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
2021-11-22T02:22:48.867-0800 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'C:\Users\Kiet\git\korge-hello-world\build\esbuild\node_modules\esbuild\esbuild.exe'' finished with exit value -1 (state: FAILED)
2021-11-22T02:22:48.867-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Execute exec for :browserReleaseEsbuild' completed
2021-11-22T02:22:48.868-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Executing task ':browserReleaseEsbuild'' completed
2021-11-22T02:22:48.868-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Snapshot outputs after executing task ':browserReleaseEsbuild'' completed
2021-11-22T02:22:48.868-0800 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Removed task artifact state for task ':browserReleaseEsbuild' from context.
2021-11-22T02:22:48.869-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Task :browserReleaseEsbuild'
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Task :browserReleaseEsbuild' completed
2021-11-22T02:22:48.869-0800 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 479: dispatching BuildEvent[event=org.gradle.internal.build.event.types.DefaultTaskFinishedProgressEvent@60fc9a97]
2021-11-22T02:22:48.870-0800 [INFO] [org.gradle.execution.plan.DefaultPlanExecutor] :browserReleaseEsbuild (Thread[Execution worker for ':',5,main]) completed. Took 0.006 secs.
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.DefaultExecutionPlan] Node :browserReleaseEsbuild failed
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.DefaultExecutionPlan] Node :runJsRelease completed, executed: false
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.Node] Checking if all dependencies are complete for :runJs
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.Node] All dependencies are complete for :runJs
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.TaskNode] Checking if all must successors are complete for :runJs
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.TaskNode] Checking if all finalizing successors are complete for :runJs
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.TaskNode] All task dependencies are complete for :runJs
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.DefaultExecutionPlan] Node :runJs completed, executed: false
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.DefaultExecutionPlan] Node :browserReleaseEsbuild completed, executed: true
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.Node] Checking if all dependencies are complete for :runJsRelease
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.Node] All dependencies are complete for :runJsRelease
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.TaskNode] Checking if all must successors are complete for :runJsRelease
2021-11-22T02:22:48.870-0800 [DEBUG] [org.gradle.execution.plan.TaskNode] Checking if all finalizing successors are complete for :runJsRelease
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.execution.plan.TaskNode] All task dependencies are complete for :runJsRelease
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': released lock on :
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.112 completed (1 worker(s) in use)
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': released lock on root.1.112
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':',5,main]] finished, busy: 40.711 secs, idle: 0.048 secs
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 2,5,main]] finished, busy: 0.0 secs, idle: 40.759 secs
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 7,5,main]] finished, busy: 0.0 secs, idle: 40.758 secs
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 4,5,main]] finished, busy: 0.0 secs, idle: 40.759 secs
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 5,5,main]] finished, busy: 0.0 secs, idle: 40.759 secs
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Daemon worker Thread 3,5,main]] finished, busy: 0.0 secs, idle: 40.759 secs
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 3,5,main]] finished, busy: 0.0 secs, idle: 40.759 secs
2021-11-22T02:22:48.871-0800 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 6,5,main]] finished, busy: 0.0 secs, idle: 40.759 secs
2021-11-22T02:22:48.872-0800 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskExecutionGraph] Timing: Executing the DAG took 40.761 secs
2021-11-22T02:22:48.872-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Run tasks'
2021-11-22T02:22:48.872-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Run tasks' completed
2021-11-22T02:22:48.872-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Run main tasks'
2021-11-22T02:22:48.872-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Run main tasks' completed
2021-11-22T02:22:48.873-0800 [DEBUG] [org.jetbrains.kotlin.gradle.plugin.statistics.KotlinBuildStatHandler] Executing [class org.jetbrains.kotlin.gradle.plugin.statistics.KotlinBuildStatHandler.buildFinished]
2021-11-22T02:22:48.875-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Execute 'allprojects {}' action' started
2021-11-22T02:22:48.875-0800 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: acquired lock on :
2021-11-22T02:22:48.875-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :' started
2021-11-22T02:22:48.876-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Cross-configure project :'
2021-11-22T02:22:48.876-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Cross-configure project :' completed
2021-11-22T02:22:48.876-0800 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 3: released lock on :
2021-11-22T02:22:48.876-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Execute 'allprojects {}' action'
2021-11-22T02:22:48.876-0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Execute 'allprojects {}' action' completed
2021-11-22T02:22:48.879-0800 [DEBUG] [org.jetbrains.kotlin.gradle.plugin.KotlinGradleFinishBuildHandler] [KOTLIN] Deleted session-is-alive flag file: build\kotlin\sessions\kotlin-compiler-10548765681035053025.salive
2021-11-22T02:22:48.879-0800 [DEBUG] [org.jetbrains.kotlin.gradle.plugin.KotlinGradleBuildServices] [KOTLIN] Disposed KotlinGradleBuildServices
2021-11-22T02:22:48.883-0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
Execution failed for task ':browserReleaseEsbuild'.
> A problem occurred starting process 'command 'C:\Users\Kiet\git\korge-hello-world\build\esbuild\node_modules\esbuild\esbuild.exe''

* Try:
Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
```

```
CreateProcess error=2, The system cannot find the file specified
````

![image](https://user-images.githubusercontent.com/5054996/142844759-ea3c123d-d982-4916-a049-5ca6d54ccd5c.png)

Ran again for stack trace:

```
Execution failed for task ':browserReleaseEsbuild'.
> A problem occurred starting process 'command 'C:\Users\Kiet\git\korge-hello-world\build\esbuild\node_modules\esbuild\esbuild.exe''

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':browserReleaseEsbuild'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:188)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:186)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:174)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'C:\Users\Kiet\git\korge-hello-world\build\esbuild\node_modules\esbuild\esbuild.exe''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:369)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'C:\Users\Kiet\git\korge-hello-world\build\esbuild\node_modules\esbuild\esbuild.exe'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
	... 4 more
Caused by: java.io.IOException: Cannot run program "C:\Users\Kiet\git\korge-hello-world\build\esbuild\node_modules\esbuild\esbuild.exe" (in directory "C:\Users\Kiet\git\korge-hello-world"): CreateProcess error=2, The system cannot find the file specified
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 8 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	... 9 more

```

**Annoyment level**

> How annoyed are you in a scale of 1-3 because this shitty code doesn't work properly

* [x] 1 - No rush from my side
* [ ] 2 - It is inconvenient, but I can circumvent the issue for now
* [ ] 3 - FUUUU
* [ ] 4

**Payment**

> How do you plan to compensate the time we will invest fixing this?

* [x] I will add a message with "Thanks" when merged to let you know I'm grateful
* [ ] I will also add a [meme image](https://imgflip.com/memegenerator) relevant to the issue to make you smile so we both have fun
* [ ] In fact, I'm going to add a meme here in this issue too
* [ ] I'm going to write about KorGE in my blog, spread the voice on social networks, or maybe even make a TikTok wearing a KorGE T-Shirt while dancing

> You can also consider donating some money via Github Sponsors to the person fixing the issue.

**Meme**

> Here you can put a meme to motivate us to fix the issue.

![image](https://user-images.githubusercontent.com/5054996/142845754-9d4d76bc-01f2-4a22-ab22-27177cf86d4d.png)

**Comment by Kietyo** [comment]
Just to note, this is from this repo:
https://github.com/korlibs/korge-hello-world

**Comment by soywiz** [comment]
Probably fixed here: https://github.com/korlibs/korge-hello-world/commit/0debf1063ce59a761cfda8271cd30819ba983a05
Feel free to reopen if not the case
